export const FLOW_EVENT_INIT = 'FLOW_EVENT_INIT';
export const FLOW_EVENT_CHECK_MEMBERSHIP = 'FLOW_EVENT_CHECK_MEMBERSHIP';
export const FLOW_EVENT_PRINT = 'FLOW_EVENT_PRINT';
export const FLOW_EVENT_PRINT_CASHLESS = 'FLOW_EVENT_PRINT_CASHLESS';
export const FLOW_EVENT_PAY_VIA_TPAI = 'FLOW_EVENT_PAY_VIA_TPAI';
export const FLOW_EVENT_CARD_PAYMENT = 'FLOW_EVENT_CARD_PAYMENT';
export const FLOW_STATUS_CARD_PAYMENT_SUCCESS =
  'FLOW_STATUS_CARD_PAYMENT_SUCCESS';
